name: Financial_Crimes
description: Combine wire transfers and various watchlists and enrich with rules to
  calculate a risk score to identify potentially nefarious transactions
version: '5'
author: bobw@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: financialcrimes
  parentArtefactID: bobwprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-02-14 17:00:07'
pipelines:
  pipelines/pipe_financial_crimes:
    name: pipe_financial_crimes
    description: See project description
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-14 17:00:07'
    datasets:
      inputs:
      - datasets/ds_country_watchlist
      - datasets/ds_person_watchlist
      - datasets/table_wire_transfer
      outputs:
      - datasets/all_scored_transx
      - datasets/flagged_transactions
      - datasets/table_all_transx_scored
    subgraphs:
    - subgraphs/risk_scoring
    dependencies: {}
datasets:
  datasets/ds_wire_transfers:
    name: ds_wire_transfers
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-14 17:32:42'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 17:32:42'
  datasets/ds_country_watchlist:
    name: ds_country_watchlist
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-14 17:39:36'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 17:39:36'
  datasets/ds_person_watchlist:
    name: ds_person_watchlist
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-14 18:36:45'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-14 18:36:45'
  datasets/flagged_transactions:
    name: flagged_transactions
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-15 21:02:29'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-15 21:02:29'
  datasets/all_scored_transx:
    name: all_scored_transx
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-15 21:11:31'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-15 21:11:31'
  datasets/table_wire_transfer:
    name: table_wire_transfer
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-21 15:47:42'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-21 15:47:42'
  datasets/table_all_transx_scored:
    name: table_all_transx_scored
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-02-21 15:53:12'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-02-21 15:53:12'
templates: {}
jobs:
  jobs/job_fin_crimes:
    name: job_fin_crimes
    description: ''
    fabricUID: 9631
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 1 ? *
    timeout: null
    alerting:
      emails: bobw@prophecy.io
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/pipe_financial_crimes
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-02-20 18:22:09'
    author: bobw@prophecy.io
  jobs/job_fincrimes_airflow:
    name: job_fincrimes_airflow
    description: ''
    fabricUID: 9770
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pipe_financial_crimes
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-02-20 19:49:37'
    author: bobw@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-02-14 17:00:07'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs:
  subgraphs/risk_scoring:
    name: risk_scoring
    description: ''
    author: bobw@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2024-02-20 19:16:52'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.3
    isDefault: true
    author: null
    createdAt: '2024-02-14 16:59:15'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-02-14 16:59:15'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
